server:
  port: 8900

spring:
  rabbitmq:
    addresses: 129.211.28.148:5672
    username: guest
    password: guest
    virtual-host: famous-product-ranking
    listener:
      simple:
        retry:
          enabled: false #开启消费者重试
          max-attempts: 3 #最大重试次数
          initial-interval: 10000 #重试间隔次数

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://129.211.28.148:3306/test_order?useUnicode=true&characterEncoding=utf8
          username: root
          password: 11a85b4d6acc43538b2324e3a97548ca
          driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  # 配置日志(控制台打印)
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true # 开启二级缓存
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/xml/*.xml
