server:
  port: 8899

mybatis-plus:
  # 配置日志(控制台打印)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true # 开启二级缓存
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mybatisMapper/*.xml

spring:
  application:
    name: spring
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://129.211.28.148:3306/springcloud_01?useUnicode=true&characterEncoding=utf8
          username: root
          password: 11a85b4d6acc43538b2324e3a97548ca
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 129.211.28.148
    port: 6381
    timeout: 1000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
